config/routes.rb
Amway::Application.routes.draw do

  root 'mains#index'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'

  resources :payment_deliveries do
    get :admin_index, as: :admin, on: :collection
  end
  resources :subsections
  resources :brands do
    get :admin_index, as: :admin, on: :collection
  end

  resources :user_infos do
    get :admin_index, as: :admin, on: :collection
    patch :update_from_site, on: :member
    post :add_request, on: :collection
  end

  resources :orders do
    get :admin_index, as: :admin, on: :collection
    post :accept_order, as: :accept, on: :collection
    get :success, on: :collection
  end
  resources :comments do
    get :admin_index, as: :admin, on: :collection
  end
  resources :products
  resources :photogallereis
  resources :shares do
    get :admin_index, as: :admin, on: :collection
  end
  resources :site_news do
    get :admin_index, as: :admin, on: :collection
  end
  resources :bisneses do
    get :admin_index, as: :admin, on: :collection
  end
  resources :contacts do
    get :admin_index, as: :admin, on: :collection
  end
  resources :mains do
    get :admin_index, as: :admin, on: :collection
  end
  resources :catalogs do
    get :admin_index, as: :admin, on: :collection
    post :add_comment, on: :collection
    get :discount, on: :collection
  end
  get 'catalogs/:code/section' => 'catalogs#section', as: :section_catalog
  get 'catalogs/:code/:brand_id/brand' => 'catalogs#brand', as: :brand_catalogs
  get 'catalogs/:code/:sub_id/section' => 'catalogs#subsection', as: :catalog_subsection
  get 'admin' => 'user_infos#admin_index'
  get 'sitemap' => 'application#sitemap'

  

end

app/models/share.rb
class Share < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
  has_attached_file :picture, styles: {mini: '48x48#', site: '971x400#', admin: '450x', banner: '259x', main: '1248x' }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  default_scope  {where(active: true).order(created_at: :desc) }

  scope :show_main, -> {where show_main: true}

  def next
    ids_db = self.class.select(:id).order(created_at: :desc)
    ids = []
    unless ids_db.nil?
      ids_db.each {|db| ids << db.id}
    end
    ids[ids.index(id) + 1]
  end

  def prev
    ids_db = self.class.select(:id).order(created_at: :desc)
    ids = []
    unless ids_db.nil?
      ids_db.each {|db| ids << db.id}
    end
    ids[ids.index(id) - 1]
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter only: [:edit, :update, :show, :destroy] do
    @shares = Share.unscoped.find params[:id]
  end
  add_breadcrumb 'Акции', :shares_path

  def index
    @shares = Share.page(params[:page]).per(5)
  end

  def admin_index
    @shares = Share.unscoped.order(active: :desc, created_at: :desc).page(params[:page]).per(20)
  end

  def new
    @shares = Share.new
    @shares.build_seo
  end

  def create
    @shares = Share.new(request_params)
    if @shares.save()
      redirect_to admin_shares_path
    else
      render 'new'
    end
  end

  def edit
    @shares.build_seo if @shares.seo.nil?
  end

  def update
    if @shares.update(request_params)
      redirect_to admin_shares_path
    else
      render 'edit'
    end
  end

  def show
    add_breadcrumb @shares.name
  end

  def destroy
    if @shares.destroy
      redirect_to admin_shares_path
    else
      render 'index'
    end
  end

  def request_params
    params.require(:share).permit(:name, :anons, :detail, :picture, :date_from, :date_to, :show_main, :active, seo_attributes:[:keywords, :description, :title])
  end
end

app/helpers/shares_helper.rb
module SharesHelper
  def getLastShares
    Share.take(3)
  end
end

app/views/shares/_actions.html.slim
.ui.compact.menu(style='float: right')
 .ui.simple.dropdown.item
  |Действия
  i.dropdown.icon
  .menu
   =link_to 'Разводящая', admin_shares_path, class: 'item' unless params[:action] == 'admin_index'
   -unless params[:action] == 'new' || params[:action] == 'edit'
    =link_to 'Добавить', new_share_path, class: 'item'
    =link_to 'Редактировать', edit_share_path(params[:id]), class: 'item' if params[:id].present?
   =link_to 'Удалить', share_path(params[:id]), class: 'item', method: :delete, data: {confirm: 'Удалить текущую акцию?'} if params[:id].present?

app/views/shares/admin_index.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Содержимое странички с акциями
=render 'actions', el: @shares
.clearfix
br
.ui.massive.aligned.divided.list
  -unless @shares.blank?
    -@shares.each do |share|
      .item
        .right.floated.content
          .ui.button=link_to 'Удалить', share_path(share), method: :delete, data: {confirm: 'Удалить эту акцию?'}
        -if share.picture.present?
          =link_to (image_tag share.picture.url(:mini)), edit_share_path(share), class: 'ui avatar image'
        .content
          =link_to "#{share.name}  #{'(Не активная)' unless share.active }", edit_share_path(share), class: "#{'non-active' unless share.active }"
          .date=share.created_at.strftime('%d.%m.%Y %H:%M:%S')
    br
=paginate @shares, theme: 'semantic_ui'

app/views/shares/edit.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Редактировать
=render 'actions', el: @shares
.clearfix
br
.ui.pointing.secondary.menu
  =link_to 'Основное', '', class: 'item active', data: {tab: 'main'}
  =link_to 'SEO', '', class: 'item', data: {tab: 'seo'}
=form_for @shares, html: {class: 'ui form', multipart: true } do |f|
 .ui.tab.segment.active(data-tab='main')
  .four.fields
   .field
     .ui.toggle.checkbox
      =f.check_box :active, {}, 1, 0
      =f.label :active, 'Активная'
   .field
     .ui.toggle.checkbox
       =f.check_box :show_main, {}, 1, 0
       =f.label :show_main, 'Показывать на главной'
  .field
    =f.label :name
    =f.text_field :name, placeholder: 'Название'
  .field
    -if @shares.picture.present?
      label Изображение для анонса
      =image_tag @shares.picture.url(:admin)
      br
    label Изображение для анонса
    =f.file_field :picture
  .field
    =f.label :anons
    =f.cktext_area :anons, ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}
  .field
    =f.label :detail
    =f.cktext_area :detail, ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}
  .two.fields
    .field
      =f.label :date_from
      =f.text_field :date_from,  placeholder: 'Дата начала'
    .field
      =f.label :date_to
      =f.text_field :date_to,  placeholder: 'Дата окончания'

 .ui.tab.segment(data-tab='seo')
  =f.fields_for :seo do |seo|
   .field
    =seo.label :title, 'Заголовок браузера'
    =seo.text_field :title, placeholder: 'Заголовок браузера'
   .field
    =seo.label :keywords
    =seo.text_field :keywords,placeholder:'Ключевые слова'
   .field
    =seo.label :description, 'Описание'
    = seo.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'mini', language: 'ru', startupMode: 'source'}
 .field
  =f.submit 'Сохранить', class: 'ui primary button'
coffee:
  $('.menu .item').tab()

app/views/shares/index.html.slim
=render '/layouts/breadcrumbs'
-object = Seo.new(title: 'Акции', keywords: 'акции компания', description: 'Акции компании Amway')
=render '/layouts/seo', meta: object
h1.ui.header Акции
.shares
  .ui.massive.aligned.divided.list
    -unless @shares.blank?
      -@shares.each do |share|
        .item
          -if share.picture.present?
            =link_to (image_tag share.picture.url(:banner)), share_path(share), class: 'ui image'
          .content
            .name=link_to share.name, share_path(share)
            .desc=share.anons.html_safe
          .date=share.created_at.strftime('%d.%m.%Y')
      br
  =paginate @shares, theme: 'semantic_ui'

app/views/shares/new.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Добавить
=render 'actions', el: @shares
.clearfix
br
.ui.pointing.secondary.menu
  =link_to 'Основное', '', class: 'item active', data: {tab: 'main'}
  =link_to 'SEO', '', class: 'item', data: {tab: 'seo'}
=form_for @shares, html: {class: 'ui form', multipart: true } do |f|
 .ui.tab.segment.active(data-tab='main')
  .four.fields
   .field
    .ui.toggle.checkbox
      =f.check_box :active, {checked: true}, 1, 0
      =f.label :active, 'Активная'
   .field
     .ui.toggle.checkbox
      =f.check_box :show_main, {checked: true}, 1, 0
      =f.label :show_main, 'Показывать на главной'
  .field
    =f.label :name
    =f.text_field :name, placeholder: 'Название'
  .field
    label Изображение для анонса
    =f.file_field :picture
  .field
    =f.label :anons
    =f.cktext_area :anons, ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}
  .field
    =f.label :detail
    =f.cktext_area :detail, ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}
  .two.fields
   .field
    =f.label :date_from
    =f.text_field :date_from, placeholder: 'Дата начала'
   .field
    =f.label :date_to
    =f.text_field :date_to, placeholder: 'Дата окончания'

 .ui.tab.segment(data-tab='seo')
  =f.fields_for :seo do |seo|
   .field
    =seo.label :title, 'Заголовок браузера'
    =seo.text_field :title, placeholder: 'Заголовок браузера'
   .field
    =seo.label :keywords
    =seo.text_field :keywords,placeholder:'Ключевые слова'
   .field
    =seo.label :description, 'Описание'
    =seo.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'mini', language: 'ru', startupMode: 'source'}
 .field
  =f.submit 'Добавить', class: 'ui primary button'

coffee:
 $('.menu .item').tab()

app/views/shares/show.html.slim
=render '/layouts/breadcrumbs'
-unless @shares.seo.nil?
  =render '/layouts/seo', meta: @shares.seo
-else
  =content_for :meta do
    title=@shares.name  
h1.ui.header=@shares.name
.shares
 .ui.segment
  .ui.red.right.ribbon.medium.label="Срок действия акции с #{@shares.date_from} по #{@shares.date_to} гг."
  =image_tag @shares.picture.url(:site)
=@shares.detail.html_safe
/.nav
  -unless @shares.prev.blank?
    a.ui.labeled.icon.button.instagram href="#{share_path(@shares.prev)}"
      i.left.arrow.icon
      |Предыдущая акция
  -unless @shares.next.blank?
    a.ui.right.labeled.icon.button.instagram href="#{share_path(@shares.next)}"
      i.right.arrow.icon
      |Следующая акция