config/routes.rb
Amway::Application.routes.draw do

  root 'mains#index'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'

  resources :payment_deliveries do
    get :admin_index, as: :admin, on: :collection
  end
  resources :subsections
  resources :brands do
    get :admin_index, as: :admin, on: :collection
  end

  resources :user_infos do
    get :admin_index, as: :admin, on: :collection
    patch :update_from_site, on: :member
    post :add_request, on: :collection
  end

  resources :orders do
    get :admin_index, as: :admin, on: :collection
    post :accept_order, as: :accept, on: :collection
    get :success, on: :collection
  end
  resources :comments do
    get :admin_index, as: :admin, on: :collection
  end
  resources :products
  resources :photogallereis
  resources :shares do
    get :admin_index, as: :admin, on: :collection
  end
  resources :site_news do
    get :admin_index, as: :admin, on: :collection
  end
  resources :bisneses do
    get :admin_index, as: :admin, on: :collection
  end
  resources :contacts do
    get :admin_index, as: :admin, on: :collection
  end
  resources :mains do
    get :admin_index, as: :admin, on: :collection
  end
  resources :catalogs do
    get :admin_index, as: :admin, on: :collection
    post :add_comment, on: :collection
    get :discount, on: :collection
  end
  get 'catalogs/:code/section' => 'catalogs#section', as: :section_catalog
  get 'catalogs/:code/:brand_id/brand' => 'catalogs#brand', as: :brand_catalogs
  get 'catalogs/:code/:sub_id/section' => 'catalogs#subsection', as: :catalog_subsection
  get 'admin' => 'user_infos#admin_index'
  get 'sitemap' => 'application#sitemap'

  

end

app/models/bisnes.rb
class Bisnes < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true

  default_scope {order(sort: :asc)}
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :catalogs
  belongs_to :product
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
  has_attached_file :picture, styles: { mini: '100x', site: '100x', normal: '450x450#', detail: '300x350#' }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  scope :show_main, -> {where show_main: true}
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  belongs_to :product
  belongs_to :brand
  has_many :ratios
  has_many :comments
  has_many :orders
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true

  has_attached_file :picture, styles: { mini: '48x48#', site: '290x300!', detal: '230x'}, default_url: '/images/:style/missing.jpg'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates :name, presence: true
  before_save do
    self.code = name.to_slug_param
  end

  before_update do
    self.code = name.to_slug_param
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :catalog
  has_one :ratio, dependent: :destroy
  accepts_nested_attributes_for :ratio, allow_destroy: true

  default_scope {where(active: true).order(:created_at)}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
end

app/models/main.rb
class Main < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  # validates :name, :sename, :phone, presence: true
  validates :count, numericality: {min: 1}, allow_nil: true, allow_blank: true
  belongs_to :catalog
  belongs_to :user_info
end

app/models/photogallery.rb
class Photogallery < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :catalogs, dependent: :delete_all
  has_many :brands
  has_many :subsections
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
  has_attached_file :picture, styles: { mini: '48x48#', site: '336x249#', normal: '450x450#'}
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  default_scope {order sort: :asc}

  before_save do
    self.code = name.to_slug_param
  end

  before_update do
    self.code = name.to_slug_param
  end
end

app/models/ratio.rb
class Ratio < ActiveRecord::Base
  belongs_to :catalog
  has_one :comment
end

app/models/seo.rb
class Seo < ActiveRecord::Base
  belongs_to :main
  belongs_to :product
  belongs_to :catalog
  belongs_to :bisnes
  belongs_to :brand
  belongs_to :site_new
  belongs_to :share
  belongs_to :photogallery
  belongs_to :contact
  belongs_to :payment_delivery
end

app/models/share.rb
class Share < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
  has_attached_file :picture, styles: {mini: '48x48#', site: '971x400#', admin: '450x', banner: '259x', main: '1248x' }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  default_scope  {where(active: true).order(created_at: :desc) }

  scope :show_main, -> {where show_main: true}

  def next
    ids_db = self.class.select(:id).order(created_at: :desc)
    ids = []
    unless ids_db.nil?
      ids_db.each {|db| ids << db.id}
    end
    ids[ids.index(id) + 1]
  end

  def prev
    ids_db = self.class.select(:id).order(created_at: :desc)
    ids = []
    unless ids_db.nil?
      ids_db.each {|db| ids << db.id}
    end
    ids[ids.index(id) - 1]
  end
end

app/models/site_new.rb
class SiteNew < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
  has_attached_file :picture, styles: { mini: '48x48#', site: '150x150#', normal: '450x450#', detail: '300x350#' }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  default_scope {where(active: true).order(created_at: :desc)}


end

app/models/subsection.rb
class Subsection < ActiveRecord::Base
  belongs_to :product
  has_many :catalogs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  has_many :orders, dependent: :destroy
  validates :name, :sename, :phone, presence: true
  apply_simple_captcha message: 'Код на картинке отличается от введенного', add_to_base: true
end

app/helpers/brands_helper.rb
module BrandsHelper
  def getProducts
    products = Product.all
    products_arr = {}
    unless products.nil?
      products.each {|product| products_arr[product.name] = product.id}
    end
    products_arr
  end

  def getBrandSection section_id
    Brand.where(product_id: section_id)
  end
end

app/helpers/mains_helper.rb
module MainsHelper
  def getShares
    Share.show_main
  end

  def getNewsToMain
    SiteNew.limit 4
  end

  def getCatalog
    Product.all
  end

  def getMostPopularProduct
    ratios = Ratio.select(:id, :catalog_id).order('sum(ratio) DESC').group(:catalog_id).limit 4
    ids = []
    unless ratios.nil?
      ratios.each {|ratio| ids << ratio.catalog_id }
    end
    products = []
    catalogs = Catalog.where(id: ids)
    unless catalogs.nil?
      catalogs.each {|catalog| products << {id: catalog.id, name: catalog.name, color: catalog.product.color, picture: catalog.picture.url(:site), ratio: (catalog.ratios.sum(:ratio) / catalog.ratios.length)} }
    end
    products
  end

  def getBrandsMain
    Brand.show_main
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def getOrderType
    {1 => 'Стать партнером', 2 => 'Заказ' }
  end



  def getOrderCountsForUser session
    Order.where(session: session, order_type: 2, active: 0).count(:session) || 0
  end

  def getOrderCountsForUserByProduct session, id
    Order.where(session: session, order_type: 2, catalog_id: id, active: 0).count(:session)
  end
end

app/helpers/shares_helper.rb
module SharesHelper
  def getLastShares
    Share.take(3)
  end
end

app/views/add_comment/user_add_comment.html.slim
doctype html
html
  head
    title ="На сайт #{@host} был добавлен новый комент"
  body
   h1="На сайт #{@host} был добавлен новый комент"
   p="Пользователь #{@name}, оставил комментарий для продукта #{@product.name}:"
   p=@message
   p На данный момент комментарий не активный и не отображается на сайте, для его активации перейдите по ссылке ниже.
   p=link_to 'Перейти для активации коментария', edit_comment_url(@id)

app/views/layouts/admin/_admin_menu.html.slim
=link_to 'Главная страничка', admin_mains_path, class: "item #{'active' if params[:controller] == 'mains'}"
=link_to 'Продукция', admin_catalogs_path, class: "item #{'active' if params[:controller] == 'catalogs'}"
=link_to 'Бизнес', admin_bisneses_path, class: "item #{'active' if params[:controller] == 'bisneses'}"
=link_to 'Новости', admin_site_news_index_path, class: "item #{'active' if params[:controller] == 'site_news'}"
=link_to 'Акции', admin_shares_path, class: "item #{'active' if params[:controller] == 'shares'}"
=link_to 'Фотогалерея', new_photogallerei_path, class: "item #{'active' if params[:controller] == 'photogallereis'}"
=link_to 'Контакты', admin_contacts_path, class: "item #{'active' if params[:controller] == 'contacts'}"
=link_to 'Оплата и доставка', admin_payment_deliveries_path, class: "item #{'active' if params[:controller] == 'payment_deliveries'}"
=link_to 'Комментарии', admin_comments_path, class: "item #{'active' if params[:controller] == 'comments'}"
=link_to 'Заявки', admin_user_infos_path, class: "item #{'active' if params[:controller] == 'user_infos'}"
=link_to 'Бренды', admin_brands_path, class: "item #{'active' if params[:controller] == 'brands'}"
=link_to 'Мои подписчики', '#', class: "item #{'active' if params[:controller] == ''}"
=link_to 'Статистика заказов', '#', class: "item #{'active' if params[:controller] == ''}"

app/views/layouts/admin/index.html.slim
h2.ui.header
 |Добро пожаловать в личный кабинет администратора Amway&nbsp;(
 =current_user.email
 |)
p Здесь вы можите редактировать, добавлять информацию на сайт.

app/views/simple_captcha/_simple_captcha.html.slim
.simple_captcha
  .simple_captcha_image
    =simple_captcha_options[:image]
  .simple_captcha_field
    =simple_captcha_options[:field]
    p.error_captcha
.clearfix