config/routes.rb
Amway::Application.routes.draw do

  root 'mains#index'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'

  resources :payment_deliveries do
    get :admin_index, as: :admin, on: :collection
  end
  resources :subsections
  resources :brands do
    get :admin_index, as: :admin, on: :collection
  end

  resources :user_infos do
    get :admin_index, as: :admin, on: :collection
    patch :update_from_site, on: :member
    post :add_request, on: :collection
  end

  resources :orders do
    get :admin_index, as: :admin, on: :collection
    post :accept_order, as: :accept, on: :collection
    get :success, on: :collection
  end
  resources :comments do
    get :admin_index, as: :admin, on: :collection
  end
  resources :products
  resources :photogallereis
  resources :shares do
    get :admin_index, as: :admin, on: :collection
  end
  resources :site_news do
    get :admin_index, as: :admin, on: :collection
  end
  resources :bisneses do
    get :admin_index, as: :admin, on: :collection
  end
  resources :contacts do
    get :admin_index, as: :admin, on: :collection
  end
  resources :mains do
    get :admin_index, as: :admin, on: :collection
  end
  resources :catalogs do
    get :admin_index, as: :admin, on: :collection
    post :add_comment, on: :collection
    get :discount, on: :collection
  end
  get 'catalogs/:code/section' => 'catalogs#section', as: :section_catalog
  get 'catalogs/:code/:brand_id/brand' => 'catalogs#brand', as: :brand_catalogs
  get 'catalogs/:code/:sub_id/section' => 'catalogs#subsection', as: :catalog_subsection
  get 'admin' => 'user_infos#admin_index'
  get 'sitemap' => 'application#sitemap'

  

end

app/models/payment_delivery.rb
class PaymentDelivery < ActiveRecord::Base
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
end

app/controllers/payment_deliveries_controller.rb
class PaymentDeliveriesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter only: [:edit, :update, :show, :destroy] do
    @payment_delivery = PaymentDelivery.find params[:id]
  end
  before_action only: [:index, :show] do
    @menu = PaymentDelivery.all
  end

  def index
    @payment_delivery = PaymentDelivery.first
    add_breadcrumb @payment_delivery.name
  end

  def admin_index
    @payment_deliveries = PaymentDelivery.all
  end

  def new
    @payment_delivery = PaymentDelivery.new
    @payment_delivery.build_seo
  end

  def create
    @payment_delivery = PaymentDelivery.new(request_params)
    if @payment_delivery.save()
      redirect_to admin_payment_deliveries_path
    else
      render 'new'
    end
  end

  def edit
    @payment_delivery.build_seo if @payment_delivery.seo.nil?
  end

  def update
    if @payment_delivery.update(request_params)
      redirect_to admin_payment_deliveries_path
    else
      render 'edit'
    end
  end

  def show
    add_breadcrumb @payment_delivery.name
  end

  def request_params
    params.require(:payment_delivery).permit(:name, :description, seo_attributes:[:keywords, :description, :title])
  end
end

app/helpers/payment_deliveries_helper.rb
module PaymentDeliveriesHelper
end

app/views/payment_deliveries/_actions.html.slim
.ui.compact.menu(style='float: right')
 .ui.simple.dropdown.item
  |Действия
  i.dropdown.icon
  .menu
   =link_to 'Разводящая', admin_payment_deliveries_path, class: 'item' unless params[:action] == 'admin_index'
   -unless params[:action] == 'new' || params[:action] == 'edit'
     =link_to 'Добавить', new_payment_delivery_path, class: 'item'

app/views/payment_deliveries/_menu.html.slim
.ui.vertical.menu
   -unless items.nil?
    -items.each do |item|
      a.item(class="#{'active' if  item.id == id}" href="#{payment_delivery_path(item)}")
        .title=item.name

app/views/payment_deliveries/admin_index.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Содержимое странички доставка и оплата
=render 'actions', el: @payment_deliveries
.clearfix
br
.ui.ordered.huge.list
 -unless @payment_deliveries.nil?
  -@payment_deliveries.each do |payment_delivery|
    =link_to payment_delivery.name, edit_payment_delivery_path(payment_delivery), class: 'item'

app/views/payment_deliveries/edit.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Редактировать
=render 'actions', el: @payment_delivery
.clearfix
br
.ui.pointing.secondary.menu
  =link_to 'Основное', '', class: 'item active', data: {tab: 'main'}
  =link_to 'SEO', '', class: 'item', data: {tab: 'seo'}
=form_for @payment_delivery, html: {class: 'ui form'} do |f|
  .ui.tab.segment.active(data-tab='main')
    .field
      =f.label :name
      =f.text_field :name, placeholder: 'Название'
    .field
      =f.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}

  .ui.tab.segment(data-tab='seo')
    =f.fields_for :seo do |seo|
      .field
        =seo.label :title, 'Заголовок браузера'
        =seo.text_field :title, placeholder: 'Заголовок браузера'
      .field
        =seo.label :keywords
        =seo.text_field :keywords,placeholder: 'Ключевые слова'
      .field
        =seo.label :description, 'Описание'
        =seo.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'mini', language: 'ru', startupMode: 'source'}
  .field
    =f.submit 'Сохранить', class: 'ui primary button'
coffee:
  $('.menu .item').tab()

app/views/payment_deliveries/index.html.slim
=render '/layouts/breadcrumbs'
-unless @payment_delivery.nil?
  =content_for :left_sidebar do
    =render 'menu', items: @menu, id: @payment_delivery.id
  -unless @payment_delivery.seo.nil?
    =render '/layouts/seo', meta: @payment_delivery.seo
  -else
    =content_for :meta do
      title Оплата и доставка
-else
  =content_for :meta do
    title Оплата и доставка
h1.ui.header=@payment_delivery.name
=@payment_delivery.description.html_safe unless @payment_delivery.nil?

app/views/payment_deliveries/new.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Добавить
=render 'actions', el: @payment_delivery
.clearfix
br
.ui.pointing.secondary.menu
  =link_to 'Основное', '', class: 'item active', data: {tab: 'main'}
  =link_to 'SEO', '', class: 'item', data: {tab: 'seo'}
=form_for @payment_delivery, html: {class: 'ui form'} do |f|
  .ui.tab.segment.active(data-tab='main')
    .field
      =f.label :name
      =f.text_field :name, placeholder: 'Название'
    .field
      =f.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}

  .ui.tab.segment(data-tab='seo')
    =f.fields_for :seo do |seo|
      .field
        =seo.label :title, 'Заголовок браузера'
        =seo.text_field :title, placeholder: 'Заголовок браузера'
      .field
        =seo.label :keywords
        =seo.text_field :keywords,placeholder: 'Ключевые слова'
      .field
        =seo.label :description, 'Описание'
        =seo.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'mini', language: 'ru', startupMode: 'source'}
  .field
    =f.submit 'Добавить', class: 'ui primary button'
coffee:
  $('.menu .item').tab()

app/views/payment_deliveries/show.html.slim
=render '/layouts/breadcrumbs'
-unless @payment_delivery.nil?
  =content_for :left_sidebar do
    =render 'menu', items: @menu, id: @payment_delivery.id
  -unless @payment_delivery.seo.nil?
    =render '/layouts/seo', meta: @payment_delivery.seo
  -else
    =content_for :meta do
      title Оплата и доставка
-else
  =content_for :meta do
    title Оплата и доставка
h1.ui.header=@payment_delivery.name
=@payment_delivery.description.html_safe unless @payment_delivery.nil?