config/routes.rb
Amway::Application.routes.draw do

  root 'mains#index'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'

  resources :payment_deliveries do
    get :admin_index, as: :admin, on: :collection
  end
  resources :subsections
  resources :brands do
    get :admin_index, as: :admin, on: :collection
  end

  resources :user_infos do
    get :admin_index, as: :admin, on: :collection
    patch :update_from_site, on: :member
    post :add_request, on: :collection
  end

  resources :orders do
    get :admin_index, as: :admin, on: :collection
    post :accept_order, as: :accept, on: :collection
    get :success, on: :collection
  end
  resources :comments do
    get :admin_index, as: :admin, on: :collection
  end
  resources :products
  resources :photogallereis
  resources :shares do
    get :admin_index, as: :admin, on: :collection
  end
  resources :site_news do
    get :admin_index, as: :admin, on: :collection
  end
  resources :bisneses do
    get :admin_index, as: :admin, on: :collection
  end
  resources :contacts do
    get :admin_index, as: :admin, on: :collection
  end
  resources :mains do
    get :admin_index, as: :admin, on: :collection
  end
  resources :catalogs do
    get :admin_index, as: :admin, on: :collection
    post :add_comment, on: :collection
    get :discount, on: :collection
  end
  get 'catalogs/:code/section' => 'catalogs#section', as: :section_catalog
  get 'catalogs/:code/:brand_id/brand' => 'catalogs#brand', as: :brand_catalogs
  get 'catalogs/:code/:sub_id/section' => 'catalogs#subsection', as: :catalog_subsection
  get 'admin' => 'user_infos#admin_index'
  get 'sitemap' => 'application#sitemap'

  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :catalogs
  belongs_to :product
  has_one :seo, dependent: :destroy
  accepts_nested_attributes_for :seo, allow_destroy: true
  has_attached_file :picture, styles: { mini: '100x', site: '100x', normal: '450x450#', detail: '300x350#' }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  scope :show_main, -> {where show_main: true}
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter only: [:edit, :update, :show, :destroy] do
    @brands = Brand.find params[:id]
  end
  add_breadcrumb 'Бренды', :brands_path

  def index
    @brands = Brand.page(params[:page]).per(10)
  end

  def admin_index
    @brands = Brand.all
  end

  def new
    @brands = Brand.new
    @brands.build_seo
  end

  def create
    @brands = Brand.new(request_params)
    if @brands.save()
      redirect_to admin_brands_path
    else
      render 'new'
    end
  end

  def edit
    @brands.build_seo if @brands.seo.nil?
  end

  def update
    if @brands.update(request_params)
      redirect_to admin_brands_path
    else
      render 'edit'
    end
  end

  def show
    add_breadcrumb @brands.name
  end

  def destroy
    if @brands.destroy
      redirect_to admin_brands_path
    else
      render 'admin_index'
    end
  end

  def request_params
    params.require(:brand).permit(:name,:description, :picture, :product_id, :show_main,  seo_attributes:[:keywords, :description, :title])
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
  def getProducts
    products = Product.all
    products_arr = {}
    unless products.nil?
      products.each {|product| products_arr[product.name] = product.id}
    end
    products_arr
  end

  def getBrandSection section_id
    Brand.where(product_id: section_id)
  end
end

app/views/brands/_actions.html.slim
.ui.compact.menu(style='float: right')
 .ui.simple.dropdown.item
  |Действия
  i.dropdown.icon
  .menu
   =link_to 'Разводящая', admin_brands_path, class: 'item' unless params[:action] == 'admin_index'
   -unless params[:action] == 'new' || params[:action] == 'edit'
    =link_to 'Добавить', new_brand_path, class: 'item'
    =link_to 'Редактировать', edit_brand_path(params[:id]), class: 'item' if params[:id].present?
   =link_to 'Удалить', brand_path(params[:id]), class: 'item', method: :delete, data: {confirm: 'Удалить текущий бренд?'} if params[:id].present?

app/views/brands/admin_index.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Бренды
=render 'actions', el: @brands
.clearfix
br
-sections = getProducts
.ui.pointing.secondary.menu
 -unless sections.nil?
  -i = 0
  -sections.each_with_index do |section|
    -name = section[0]
    -key = section[1]
    =link_to name, '', class: "item #{'active' if i == 0 }", data: {tab: key}
    -i = 1
-unless sections.nil?
  -i = 0
  -sections.each_with_index do |section|
    -name = section[0]
    -key = section[1]
    .ui.tab.segment(class="item #{'active' if i == 0 }" data-tab="#{key}")
     -i = 1
     .ui.massive.aligned.divided.list
      -section_brands = getBrandSection key
      -unless section_brands.nil?
        -section_brands.each do |brand|
          .item
            .right.floated.content
              .ui.button.negative=link_to 'Удалить', brands_path(brand), method: :delete, data: {confirm: 'Удалить этот бренд?'}
            -if brand.picture.present?
              =link_to (image_tag brand.picture.url(:mini),class: 'ui middle aligned tiny image'), edit_brand_path(brand), class: 'ui image'
            .content
              =link_to brand.name , edit_brand_path(brand)
coffee:
  $('.menu .item').tab()

app/views/brands/edit.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Редактировать
=render 'actions', el: @brands
.clearfix
br
.ui.pointing.secondary.menu
  =link_to 'Основное', '', class: 'item active', data: {tab: 'main'}
  =link_to 'SEO', '', class: 'item', data: {tab: 'seo'}
=form_for @brands, html: {class: 'ui form', multipart: true } do |f|
  .ui.tab.segment.active(data-tab='main')
    .three.fields
      .field
        =f.label :name
        =f.text_field :name, placeholder: 'Название'
      .field
        =f.label :product_id
        =f.select :product_id, getProducts, selected: @brands.product_id
      .field
        .ui.toggle.checkbox style='padding-top: 10%'
          =f.check_box :show_main, {}, 1, 0
          =f.label :show_main, 'Показывать на главной'
    .field
      -if @brands.picture.present?
        label Изображение для анонса
        =image_tag @brands.picture.url(:site)
        br
      label Изображение
      =f.file_field :picture
    .field
      =f.label :description
      =f.cktext_area :description, ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}
  .ui.tab.segment(data-tab='seo')
    =f.fields_for :seo do |seo|
      .field
        =seo.label :title, 'Заголовок браузера'
        =seo.text_field :title, placeholder: 'Заголовок браузера'
      .field
        =seo.label :keywords
        =seo.text_field :keywords,placeholder:'Ключевые слова'
      .field
        =seo.label :description, 'Описание'
        =seo.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'mini', language: 'ru', startupMode: 'source'}
  .field
    =f.submit 'Сохранить', class: 'ui primary button'

coffee:
  $('.menu .item').tab()

app/views/brands/index.html.slim
h1 Brands#index
p Find me in app/views/brands/index.html.slim

app/views/brands/new.html.slim
h3.ui.header(style='float: left; padding-top: 15px') Добавить
=render 'actions', el: @brands
.clearfix
br
.ui.pointing.secondary.menu
  =link_to 'Основное', '', class: 'item active', data: {tab: 'main'}
  =link_to 'SEO', '', class: 'item', data: {tab: 'seo'}
=form_for @brands, html: {class: 'ui form', multipart: true } do |f|
  .ui.tab.segment.active(data-tab='main')
    .three.fields
      .field
        =f.label :name
        =f.text_field :name, placeholder: 'Название'
      .field
        =f.label :product_id
        =f.select :product_id, getProducts
      .field
        .ui.toggle.checkbox style='padding-top: 10%'
          =f.check_box :show_main, {checked: true}, 1, 0
          =f.label :show_main, 'Показывать на главной'
    .field
      label Изображение
      =f.file_field :picture
    .field
      =f.label :description
      =f.cktext_area :description, ckeditor: {uiColor: '#3d698e', toolbar: 'full', language: 'ru'}
  .ui.tab.segment(data-tab='seo')
    =f.fields_for :seo do |seo|
      .field
        =seo.label :title, 'Заголовок браузера'
        =seo.text_field :title, placeholder: 'Заголовок браузера'
      .field
        =seo.label :keywords
        =seo.text_field :keywords,placeholder:'Ключевые слова'
      .field
        =seo.label :description, 'Описание'
        =seo.cktext_area :description, class: 'ckeditor',  ckeditor: {uiColor: '#3d698e', toolbar: 'mini', language: 'ru', startupMode: 'source'}
  .field
    =f.submit 'Добавить', class: 'ui primary button'

coffee:
  $('.menu .item').tab()

app/views/brands/show.html.slim
h1 Brands#show
p Find me in app/views/brands/show.html.slim